
services:
  api:
    container_name: pedidos-ecommerce-api
    build:
      context: ./PedidosECommerce
      dockerfile: Dockerfile
    ports:
      - "4652:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
      - rabbitmq
    networks:
      - pedidos-networks

  sqlserver:
    image: rapidfort/microsoft-sql-server-2019-ib:latest
    ports:
    - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SenhaForte123!"
    volumes:
      - sqlserver-volume:/var/opt/mssql
    networks:
      pedidos-networks:
        aliases:
          - "sql"

  rabbitmq:
    image: 'rabbitmq:3.13-management'
    container_name: dotnet_rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - pedidos-networks
    

volumes:
  sqlserver-volume:
  rabbitmq-volume:

networks:
  pedidos-networks:
    driver: bridge