
services:
  api:
    container_name: pedidos-ecommerce-api
    build:
      context: ./PedidosECommerce
      dockerfile: Dockerfile
    ports:
      - "4652:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
      - rabbitmq
      - mongo
    networks:
      - pedidos-networks

  sqlserver:
    image: rapidfort/microsoft-sql-server-2019-ib:latest
    ports:
    - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SenhaForte123!"
    volumes:
      - sqlserver-volume:/var/opt/mssql
    networks:
      pedidos-networks:
        aliases:
          - "sql"

  rabbitmq:
    image: 'rabbitmq:3.13-management'
    container_name: dotnet_rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - pedidos-networks
    
  mongo:
    image: mongo:7
    container_name: pedidos-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-volume:/data/db
    environment:
      - MONGO_INITDB_DATABASE=PedidosAudit
    networks:
      - pedidos-networks
   
  redis:
    image: redis:7
    container_name: pedidos-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
    networks:
      - pedidos-networks

volumes:
  sqlserver-volume:
  rabbitmq-volume:
  mongo-volume:
  redis-volume:

networks:
  pedidos-networks:
    driver: bridge